### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by benna86** [rabauke/harbour-sailbabel#2]
I find inconvenient to load the dictionary every time the application starts, in particular with large dictionaries the loading time is too long.

I have written some code to save the dictionary in a SQL database, if you are interested I can create a pull request.

Best,
Stefano

**Comment by rabauke** [comment]
Dear Stefano,
> I find inconvenient to load the dictionary every time the application
> starts, in particular with large dictionaries the loading time is too long.
>
> I have written some code to save the dictionary in a SQL database, if
> you are interested I can create a pull request.

this sounds interesting.  If you make a pull request I will have a look 
at this (as soon as time permits).

Heiko
