### ISSUE TITLE
Provide an option for a default dictionary

### ISSUE THREAD

**Issue by Pohli** [rabauke/harbour-sailbabel#6]
It's very annoying that I have to load a dictionary each time starting Sailbabel. Also I use only one dictionary. It would be nice if I could define a default dictionary that would be automatically loaded at startup.

**Comment by rabauke** [comment]
Thanks for your suggestion.  This is actually something that I had already considered.  The main reason why the last used dictionary is not loaded on default is, that loading the dictionary may take a while and currently there is also to way to cancel loading an dictionary. Thus, it may be inconvenient if a default directory is loaded, though one wants to work actually with another one.

I think a good solution would be if users could configure whether the last used dictionary is not loaded automatically or not.

**Comment by Pohli** [comment]
Yes, an option would be nice.

**Comment by rabauke** [comment]
Fixed via b7d3c9d.
